# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'idoubs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for idoubs
pod 'Alamofire', '~> 4.5'	
pod 'KRProgressHUD'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'
pod 'MBProgressHUD'
end
